### ISSUE TITLE
Consider build script integration?

### ISSUE THREAD

**Issue by phil-opp** [DianaNites/cargo-sysroot#1]
Hi, I just found this project and I really like your approach of using `.cargo/config` so that standard cargo works.

Have you thought about providing a `lib.rs` with a `build_sysroot(path)` function? This function could be used in a build script so that one no longer needs to manually run `cargo sysroot` after each Rust update.

**Comment by phil-opp** [comment]
I just tried to implement something like this, but it seems like Cargo tries to build the dependencies before running the build script. So I think that this approach won't work unfortunately.

**Comment by DianaNites** [comment]
Completely missed this issue, apparently github wasn't having me watch the repository :(, but yeah build scripts run too late in the processes sadly.

That does give me an idea, though.

`build.rustc` in `.cargo/config` could probably be abused for it, but it'd probably slow things down a lot since it'd run cargo to check the sysroot for each compiler invocation. Not worth it.

If you were allowed to use `.cargo/config` `alias` to.. alias built-in commands, then it could be done, but you can't do that either. It could be done with new aliases like `sbuild`, but that would kind of defeat the purpose of standard cargo working.

Shouldn't have to manually run `cargo sysroot` often enough for it to matter anyway, I suspect most people don't update their nightlies every day.

And the point is now kind of moot with the progress in std-aware cargo, with the new unstable [`build-std` feature](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) both our crates are a tad obsolete.

**Comment by phil-opp** [comment]
Thanks for replying! I agree that abusing `build.rustc` wouldn't be a good solution.



> And the point is now kind of moot with the progress in std-aware cargo, with the new unstable [`build-std` feature](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) both our crates are a tad obsolete.

Yeah, it's awesome! It already works great on my crates, the only drawback is the need to pass the `-Zbuild-std` argument every time. But I'm sure this will be improved soon.
